### ISSUE TITLE
Uploader.php missing

### ISSUE THREAD

**Issue by SebT34** [XoopsModules25x/xoopstube#20]
Hi, 

Thanks for your module :)
I have try, but i obtain error when i want to upload:
Warning: require_once(/modules/xoopstube/class/uploader.php): failed to open stream: No such file or directory in file /modules/xoopstube/class/Utility.php line 2559

Have a good day.

Seb

**Comment by zyspec** [comment]
Just comment out line 2559 in the ./modules/xoopstube/class/Utility.php file so it looks like:
// require_once __DIR__ . '/uploader.php';
This should remove the warning. The class used now is MediaUploader so it was moved from it's previous location. This 'require_once' is no longer needed.    On Tuesday, December 8, 2020, 05:05:11 AM CST, SebT34 <notifications@github.com> wrote:  
 
 


Hi,

Thanks for your module :)
I have try, but i obtain error when i want to upload:
Warning: require_once(/modules/xoopstube/class/uploader.php): failed to open stream: No such file or directory in file /modules/xoopstube/class/Utility.php line 2559

Have a good day.

Seb

**Comment by mambax7** [comment]
Thanks Zyspec, it will be committed soon.

**Comment by SebT34** [comment]
Thanks. It's working now 👍
