### ISSUE TITLE
Improper access of XoopsDB->query() result

### ISSUE THREAD

**Issue by zyspec** [XoopsModules25x/xoopstube#22]
in ./admin/main.php around rows 465-466 the code attempts to treat the `$result` object as an array. To fix this the code should be changed from:
```php
            [$lid, $title] = $GLOBALS['xoopsDB']->fetchrow($result);
            $item_tag = $result['item_tag'];

```
to the single line:
```php
            [$lid, $title, $item_tag, $vidid] = $GLOBALS['xoopsDB']->fetchrow($result);
```

**Comment by mambax7** [comment]
Thanks! Fixed in https://github.com/XoopsModules25x/xoopstube/pull/21
