### ISSUE TITLE
Wrong path for rate icons

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xoopstube#6]
Rate pictures are here:
xoopstube/assets/images/icon/

but the module goes on this path:
xoopstube/images/icon/

**Comment by mambax7** [comment]
You need to change the templates in XOOPS for your theme. 
see: https://github.com/XOOPS/XoopsCore25/pull/481

**Comment by cesagonchu** [comment]
Ok, I was using xbootstrap. With your corrections, the icons appear, thank you. :-)
