### ISSUE TITLE
Module not work with Xoops 2.5.8.1

### ISSUE THREAD

**Issue by nicemen** [XoopsModules25x/xoopstube#7]
I have a problem with XoopsTube under Xoops 2.5.8.1

I installed the module without problem but I can not access it on the admin side it's the same there are certain menu (main, modified, broken, ...) which generates the same error:

Error: Class 'XoopstubeTree' not found (error without debug mode)

Error in online debug mode:

Warning: include_once (/modules/xoopstube/class/xoopstubetree.php): failed to open stream: No such file or directory in file /modules/xoopstube-master/admin/admin_header.php line 58

Warning: include_once (): Failed opening '/modules/xoopstube/class/xoopstubetree.php' for inclusion (include_path = '.: / Usr / share / php') in file /modules/xoopstube-master/admin/admin_header.php Line 58

Error: Class 'XoopstubeTree' not found in file /modules/xoopstube-master/admin/main.php line 23

**Comment by zyspec** [comment]
This is a problem because the module was downloaded directly from GitHub and then uploaded to the server.  When downloading from GitHub the directory is named 'xoopstube-master' when downloaded. You must rename the directory to 'xoopstube' _before_ installing the module.
