### ISSUE TITLE
Typo in Thumbnails section

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xoopstube#9]
In the preferences of the module, in the "Use Thumbnails:" section, there is this sentence:

> WF-Links will use thumb nails for images. Set to 'No' to use orginal image if the server does not support this option.

I assume the correct sentence is:

> XoopsTube will use thumb nails for images. Set to 'No' to use orginal image if the server does not support this option.

**Comment by zyspec** [comment]
This was fixed in #14  (87957db) ...
